version: '3.8'

services:
  article-explainer:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./docs:/app/docs:ro
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    command: ["/app/.venv/bin/python", "-m", "streamlit", "run", "article_explainer.py", "--server.port=8501", "--server.address=0.0.0.0"]
